config/routes.rb
Rails.application.routes.draw do
  resources :uruns
  resources :markas
  get 'uruns/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'markas#index' 
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/marka.rb
class Marka < ApplicationRecord
    has_many :uruns, dependent: :destroy
end

app/models/urun.rb
class Urun < ApplicationRecord
    belongs_to :marka
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def markaadd
  end
 
end

app/controllers/markas_controller.rb
class MarkasController < ApplicationController
  before_action :set_marka, only: %i[ show edit update destroy ]

  # GET /markas or /markas.json
  def index
    @markas = Marka.all
  end

  # GET /markas/1 or /markas/1.json
  def show
  end

  # GET /markas/new
  def new
    @marka = Marka.new
  end

  # GET /markas/1/edit
  def edit
  end

  # POST /markas or /markas.json
  def create
    @marka = Marka.new(marka_params)

    respond_to do |format|
      if @marka.save
        format.html { redirect_to marka_url(@marka), notice: "Marka Eklendi" }
        format.json { render :show, status: :created, location: @marka }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @marka.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markas/1 or /markas/1.json
  def update
    respond_to do |format|
      if @marka.update(marka_params)
        format.html { redirect_to marka_url(@marka), notice: "Marka Güncellendi" }
        format.json { render :show, status: :ok, location: @marka }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @marka.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markas/1 or /markas/1.json
  def destroy
    @marka.destroy

    respond_to do |format|
      format.html { redirect_to markas_url, notice: "Marka silindi" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marka
      @marka = Marka.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marka_params
      params.require(:marka).permit(:name)
    end
end

app/controllers/uruns_controller.rb
class UrunsController < ApplicationController
  before_action :set_urun, only: %i[ show edit update destroy ]

  # GET /uruns or /uruns.json
  def index
    @uruns = Urun.all
    
  end

  # GET /uruns/1 or /uruns/1.json
  def show
  end

  # GET /uruns/new
  def new
    @urun = Urun.new
  end

  # GET /uruns/1/edit
  def edit
  end

  # POST /uruns or /uruns.json
  def create
    @urun = Urun.new(urun_params)

    respond_to do |format|
      if @urun.save
        format.html { redirect_to urun_url(@urun), notice: "Ürün Eklendi" }
        format.json { render :show, status: :created, location: @urun }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @urun.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uruns/1 or /uruns/1.json
  def update
    respond_to do |format|
      if @urun.update(urun_params)
        format.html { redirect_to urun_url(@urun), notice: "Ürün Güncellendi" }
        format.json { render :show, status: :ok, location: @urun }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @urun.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uruns/1 or /uruns/1.json
  def destroy
    @urun.destroy

    respond_to do |format|
      format.html { redirect_to uruns_url, notice: "Ürün Silindi" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_urun
      @urun = Urun.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def urun_params
      params.require(:urun).permit(:name, :marka_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/markas_helper.rb
module MarkasHelper
end

app/helpers/urun_helper.rb
module UrunHelper
end

app/helpers/uruns_helper.rb
module UrunsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Markalar", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= link_to "Ürünler", uruns_path, class: "nav-link" %>
      
      
    </ul>
    
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/markaadd.html.erb
deneme

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Dia</title>
  </head>
  <body>
  <%= render 'home/header' %>
    <h1 class="d-flex justify-content-center">Dia Yazılım E-ticaret</h1>

    <div class="container">
      <br>
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/markas/_form.html.erb
<%= form_with(model: marka) do |form| %>
  <% if marka.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(marka.errors.count, "error") %> prohibited this marka from being saved:</h2>

      <ul>
        <% marka.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Marka, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit 'Kaydet' %>
  </div>
<% end %>

app/views/markas/_marka.html.erb
<div id="<%= dom_id marka %>">
  <p>
    <strong>Marka No:</strong>
    <%= marka.id %>
  </p>

  <p>
    <strong>Adı:</strong>
    <%= marka.name %>
  </p>

</div>

app/views/markas/edit.html.erb
<h1>Marka Düzenleme</h1>

<%= render "form", marka: @marka %>

<br>

<div>
  <%= link_to "İncele", @marka %> |
  <%= link_to "Markalara Git", markas_path %>
</div>

app/views/markas/index.html.erb
<h1 class="d-flex justify-content-center">Markalar</h1>
<div id="markas">
<table class="table table-bordered table-striped" >
  <thead class="thead-dark">
    <tr>
      <th scope="col">Marka No</th>
      <th scope="col">Marka Adı </th>
      <th scope="col">Göster </th>
      <th scope="col">Düzenle </th>
      <th scope="col">Sil </th>   
    </tr>
    
  </thead>
  <tbody>
  <% @markas.each do |marka| %>
 
    <tr>
      <td><%= marka.id%></td>
      <td><%= marka.name%></td>
      <td><%= link_to "Göster", marka %></td>
      <td><%= link_to "Düzenle", edit_marka_path(marka) %></td>
      <td><%= link_to "Sil", marka, method: :delete, data: {confirm: 'Marka Silinecek'} %></td>
    </tr>
   <% end %>
  </tbody>
</table>
</div>
<%= link_to "Marka Ekle", new_marka_path %>

app/views/markas/new.html.erb
<h1>Marka Ekle</h1>

<%= render "form", marka: @marka %>

<br>

<div>
  <%= link_to "Markalara Git", markas_path %>
</div>

app/views/markas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @marka %>

<div>
  <%= link_to "Markayı Güncelle", edit_marka_path(@marka) %> |
  <%= link_to "Markalara Git", markas_path %>

  <%= button_to "Markayı Sil", @marka, method: :delete %>
</div>

app/views/uruns/_form.html.erb
<%= form_with(model: urun) do |form| %>
  <% if urun.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(urun.errors.count, "error") %> prohibited this urun from being saved:</h2>

      <ul>
        <% urun.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, 'Ürün Adı',style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
  <%@markalarListesi = Marka.all
  %>
 <%= form.select(:marka_id) do %>
    <% @markalarListesi.each do |l| -%>
      <%= content_tag(:option, l.name, value: l.id) %>
    <% end %>
<% end %>
  <br>

    <!--<%= form.number_field :marka_id %>
        <%= form.label :marka_id, style: "display: block" %>
    <%= form.number_field :marka_id %>
    
    -->
  </div>

  <div>
    <%= form.submit 'Kaydet' %>
  </div>
<% end %>

app/views/uruns/_urun.html.erb
<div id="<%= dom_id urun %>">
  <p>
    <strong>Ürün No:</strong>
    <%= urun.id %>
  </p>

  <p>
    <strong>Marka:</strong>
    <%= Marka.find(urun.marka_id).name %>
  </p>

  <p>
    <strong>Ürün:</strong>
    <%= urun.name %>
  </p>


</div>

app/views/uruns/edit.html.erb
<h1>Ürün Düzenleme</h1>

<%= render "form", urun: @urun %>

<br>

<div>
  <%= link_to "Ürünü Göster", @urun %> |
  <%= link_to "Ürünlere Git", uruns_path %>
</div>

app/views/uruns/index.html.erb
<h1 class="d-flex justify-content-center">Ürünler</h1>
<div id="markas">
<table class="table table-bordered table-striped" >
  <thead class="thead-dark">
    <tr>
      <th scope="col">Ürün No</th>
      <th scope="col">Marka Adı </th>
       <th scope="col">Ürün Adı </th>
      <th scope="col">Göster </th>
      <th scope="col">Düzenle </th>
      <th scope="col">Sil </th>   
    </tr>
    
  </thead>
  <tbody>
  <% @uruns.each do |urun| %> 
    <tr>
     <td><%= urun.id%></td>
      <td><%= Marka.find(urun.marka_id).name%> </td>
       <td><%= urun.name%></td>
      <td><%= link_to "Göster", urun %></td>
      <td><%= link_to "Düzenle", edit_urun_path(urun) %></td>
      <td><%= link_to "Sil", urun, method: :delete, data: {confirm: 'Ürün Silinecek'} %></td>
    </tr>
   <% end %>
  </tbody>
</table>
</div>
<%= link_to "Ürün Ekle", new_urun_path %>

app/views/uruns/new.html.erb
<h1>Ürün Ekle</h1>

<%= render "form", urun: @urun %>

<br>

<div>
  <%= link_to "Ürünlere Git", uruns_path %>
</div>

app/views/uruns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @urun %>

<div>
  <%= link_to "Düzenle", edit_urun_path(@urun) %> |
  <%= link_to "Ürünlere Git", uruns_path %>

  <%= button_to "Sil", @urun, method: :delete %>
</div>